#!/bin/sh

echo "Switching to branch master"
git checkout nextjs-site

echo "Building app"
npm run prod

echo "Deploying files to server"
rsync -avP build/ jdrentlaw@45.56.95.147:/var/www/thedmsshield.com/
echo "Deployment complete"